name: Hola mundo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hola: #Nombre representativo
    runs-on: ubuntu-latest # SO de ejecuciÃ³n

    steps:
    - name: Hola Mundo 
      run: echo "Hola Mundo"

    - name: Touch file
      run: touch hola.txt

    - name: Set text
      run : echo "Hola Mundo" >> hola.txt

    - name: Read file
      run: cat hola.txt
  
  other:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: LS 
      run: ls -al
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: latest
    - name: node version
      run: node --version
    - name: PHP
      run: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: php version
      run: php --version
    